#!/usr/bin/env ruby -wKU

# I own /usr/local/bin. That is where this file must live.

puts "\\documentclass{amsart}"
puts "\\usepackage{amssymb,latexsym}"
puts
puts "\\pagestyle{empty}"
puts
puts "\\begin{document}"
puts "  \\title{\\bf Homework \\#1}"
puts "  \\author{Luke DeWitt\\\\"
puts "  MORE STUFF MAYBE}"
puts "  \\maketitle"
puts
puts "\\end{document}"