#!/usr/bin/env ruby -wKU

# I own /usr/local/bin. That is where this file must live.

puts "Enter the name of your project:"

project = gets.strip

system "mkdir -p #{project}/{bin,config,data,db,doc,lib,spec,views}"
system "touch #{project}/README.md"
system "mkdir #{project}/lib/#{project}"
system "touch #{project}/lib/#{project}.rb"
system "mkdir #{project}/spec/#{project}"
system "touch #{project}/spec/#{project}_spec.rb"
